### PR TITLE
Simplify Service Registry, Pass in References as Dependencies to Prevent Nil Pointer Errors

### LINKED ISSUE #214: Simulator is generating nil collation body requests
To reproduce:

- Start the observer service connected a geth node
- The geth node is running with `--dev` flag and not advancing the chain
- See that there is nothing simulated every 15 seconds

This line has `req == nil`:
https://sourcegraph.com/github.com/prysmaticlabs/geth-sharding/-/blob/sharding/simulator/service.go?utm_source=share#L99

Is this because this is a fresh VMC with no notaries or collations? 
Or could it be due to the period ID not advancing since the `--dev` geth node only mines a new block on transaction (to save cpu).

### PR DESCRIPTION
**Pull request by rauljordan**
Hi all,

This resolves #214 and #215.

### What Was Wrong?

Previously, we were starting each service in our sharding node by simply iterating over the service registry map.
```go
for _, kind := range s.serviceTypes {
	// Start each service in order of registration.
	s.services[kind].Start()
}
```
Go, however, does not order keys in maps, so we are not preserving the order of registration of each service. That is, the shardDB could be initialized last and we do not want this to happen.

Additionally, our previous approach to a sharding registry would pass in a copy of each dependency into corresponding services instead of passing in a reference. This would mean that if a service would set a property in its Start function, its dependent services would not see this updated property as they have a copy but not a pointer to the original service they depend on.

### How It Was Fixed

To solve the first problem, we keep track of a `serviceTypes` slice which is inherently ordered by time of appending. When we register each service, we do so in the order that makes sense and append to this `serviceTypes` slice. Then, we initialize each service in order as follows:

```go
for _, kind := range s.serviceTypes {
	// Start each service in order of registration.
	s.services[kind].Start()
}
```

To solve the second issue, we simplify the register and fetchservice functions in our node as follows:

```go
// registerService appends a service constructor function to the service registry of the
// sharding node.
func (s *ShardEthereum) registerService(service sharding.Service) error {
	kind := reflect.TypeOf(service)
	if _, exists := s.services[kind]; exists {
		return fmt.Errorf("service already exists: %v", kind)
	}
	s.services[kind] = service
	s.serviceTypes = append(s.serviceTypes, kind)
	return nil
}

// fetchService returns a reference to an original service stored in the service registry.
func (s *ShardEthereum) fetchService(service interface{}) error {
	element := reflect.ValueOf(service).Elem()
	if running, ok := s.services[element.Type()]; ok {
		element.Set(reflect.ValueOf(running))
		return nil
	}
	return fmt.Errorf("unknown service: %T", service)
}

```

The register function not only adds the service to the registry map, but also appends its type to the `serviceTypes` slice. The fetch service function, when passed in a pointer to a struct, will populate that pointer with the original service used at registration.

We can use these functions as follows:

```go
func (s *ShardEthereum) registerTXPool(actor string) error {
	if actor != "proposer" {
		return nil
	}
	var shardp2p *p2p.Server
	if err := s.fetchService(&shardp2p); err != nil {
		return err
	}
	pool, err := txpool.NewTXPool(shardp2p)
	if err != nil {
		return fmt.Errorf("could not register shard txpool service: %v", err)
	}
	return s.registerService(pool)
}
```

fetchService will return the proper, original service and not a copy. This means that the txpool service will have the correct dependency.

Another problem in our approach was that we still had some code with critical dependencies happening in the registration process instead of the Start process of each service. For example, in `syncer`, we were initializing a `Shard` instance even though the shardDB service has not been started yet! Instead, we attach the shard in the syncer's Start function as a solution.

```go
func NewSyncer(...bunch of stuff) (*Syncer, error) {
	ctx, cancel := context.WithCancel(context.Background())
	errChan := make(chan error)
	responseSent := make(chan int)
	return &Syncer{config, client, dbService, shardID, nil, p2p, ctx, cancel, errChan, responseSent}, nil
}

// Start the main loop for handling shard chain data requests.
func (s *Syncer) Start() {
	log.Info("Starting sync service")
       
        // We attach a shard here and not in the NewSyncer func!!
	shard := sharding.NewShard(big.NewInt(int64(s.shardID)), s.dbService.DB())
	s.shard = shard
}
```

### CODE REVIEW

File: sharding/node/backend.go [hunk 1]
```diff
@@ -148,53 +149,50 @@ func (s *ShardEthereum) Close() {
...
 	if _, exists := s.services[kind]; exists {
 		return fmt.Errorf("service already exists: %v", kind)
 	}
 	s.services[kind] = service
-
+	s.serviceTypes = append(s.serviceTypes, kind)
 	return nil
 }
 
+// fetchService returns a reference to a service stored in the service registry.
```
Comment (rawfalafel) [inline sharding/node/backend.go]: The comments should mention that this returns a copy of the original service, since its an important gotcha. This could also return a pointer to the same service but we would have to be mindful of concurrency issues.

File: sharding/node/backend.go [hunk 2]
```diff
@@ -148,53 +149,50 @@ func (s *ShardEthereum) Close() {
...
+func (s *ShardEthereum) fetchService(service interface{}) error {
+	element := reflect.ValueOf(service).Elem()
+	if running, ok := s.services[element.Type()]; ok {
+		element.Set(reflect.ValueOf(running))
```
Comment (rawfalafel) [inline sharding/node/backend.go]: Actually, does this return a copy of the service?

File: sharding/database/database.go [hunk 3]
```diff
@@ -51,6 +51,6 @@ func (s *ShardDB) Stop() error {
 }
 
 // DB returns the attached ethdb instance.
-func (s *ShardDB) DB() ethdb.Database {
+func (s *ShardDB) DB() *ethdb.LDBDatabase {
```
Comment (prestonvanloon) [inline sharding/database/database.go]: Why change this?

File: sharding/node/backend.go [hunk 4]
```diff
@@ -148,53 +149,50 @@ func (s *ShardEthereum) Close() {
...
 	}
 	s.services[kind] = service
-
+	s.serviceTypes = append(s.serviceTypes, kind)
 	return nil
 }
 
+// fetchService returns a reference to a service stored in the service registry.
+func (s *ShardEthereum) fetchService(service interface{}) error {
+	element := reflect.ValueOf(service).Elem()
```
Comment (prestonvanloon) [inline sharding/node/backend.go]: Is there any way we can assert that service is a pointer? This would resolve some of @rawfalafel's concerns about copying data. 

This does copy the pointer value, but this is desired. However, if the user passes a value then they will receive a copy of the value, right? It might make sense to be a bit defensive from our future selves or other contributors.

File: sharding/node/backend.go [hunk 5]
```diff
@@ -228,53 +228,100 @@ func (s *ShardEthereum) registerTXPool(actor string) error {
...
+	if err := s.fetchService(&shardp2p); err != nil {
+		return err
+	}
+	var client *mainchain.SMCClient
+	if err := s.fetchService(&client); err != nil {
+		return err
+	}
+
+	// 15 second delay between simulator requests.
+	sim, err := simulator.NewSimulator(config, client, shardp2p, shardID, 15)
```
Comment (prestonvanloon) [inline sharding/node/backend.go]: I'm not sure if you addressed this in #216, but can you please change this to pass `15*time.Second`? 
It's not intuitive to pass 15 as `time.Duration` and know that this will be multipled by `time.Second` later. 

If this is more than a 3-5 line change, then we can address later.

File: sharding/proposer/service.go [hunk 6]
```diff
@@ -80,8 +83,8 @@ func (p *Proposer) proposeCollations() {
 		case <-p.ctx.Done():
 			log.Error("Proposer context closed, exiting goroutine")
 			return
-		case err := <-p.txpoolSub.Err():
-			log.Error(fmt.Sprintf("Subscriber closed: %v", err))
+		case <-p.txpoolSub.Err():
+			log.Error("Subscriber closed")
```
Comment (prestonvanloon) [inline sharding/proposer/service.go]: Is this really an error level message? 
Same comment for line 84. 

I think it should be info or debug.

File: sharding/node/backend.go [hunk 7]
```diff
@@ -138,7 +136,11 @@ func (s *ShardEthereum) Close() {
 	defer s.lock.Unlock()
 
 	for kind, service := range s.services {
-		if err := service.Stop(); err != nil {
+		fetched, ok := service.(sharding.Service)
+		if !ok {
+			return
+		}
+		if err := fetched.Stop(); err != nil {
```
Comment (terenc3t) [inline sharding/node/backend.go]: 1. when we stop the services, should we stop each in the reverse order we appended to `serviceTypes`? (i.e. does ordering matter when attempt to stop services)
2. if 1. is yes then we should use `for _, kind := range s.serviceTypes` for  `(s *ShardEthereum) Close() `

File: sharding/node/backend.go [hunk 8]
```diff
@@ -138,7 +136,11 @@ func (s *ShardEthereum) Close() {
 	defer s.lock.Unlock()
 
 	for kind, service := range s.services {
```
Comment (terenc3t) [inline sharding/node/backend.go]: 1. when we stop the services, should we stop each in the reverse order we appended to `serviceTypes`? (i.e. does ordering matter when attempt to stop services)
2. if 1. is yes then we should use `for _, kind := range s.serviceTypes` for  `(s *ShardEthereum) Close() `

File: sharding/observer/service_test.go [hunk 9]
```diff
@@ -21,7 +21,10 @@ func TestStartStop(t *testing.T) {
 	if err != nil {
 		t.Fatalf("Unable to setup p2p server: %v", err)
 	}
-	shardChainDB := database.NewShardKV()
+	shardChainDB, err := database.NewShardDB("", "", true)
```
Comment (terenc3t) [inline sharding/observer/service_test.go]: are we switching from testing using KV to an actual DB?

File: sharding/node/backend.go (hunk 8 above)
Comment (prestonvanloon) [reply sharding/node/backend.go]: I don't think it matters

**Comment by rawfalafel** [comment]
looks great :+1:
