### PR TITLE
Only deposit when --deposit is present 

### LINKED ISSUE #115: Running a notary always tries to deposit 1000ETH
To reproduce:

Deploy the contract, deposit ETH as a notary, update config.go with the contract address, then run the client as a notary again without `--deposit`.

```
geth sharding-notary --datadir=/tmp/data --networkid=1337INFO [05-13|11:15:55] Starting notary client
INFO [05-13|11:15:55] Joining notary pool
unable to deposit eth and become a notary: failed to estimate gas needed: gas required exceeds allowance or always failing transaction
```

### PR DESCRIPTION
**Pull request by prestonvanloon**
Fixes #115

### CODE REVIEW

File: sharding/client/client.go [hunk 1]
```diff
@@ -239,3 +240,7 @@ func initSMC(c *shardingClient) (*contracts.SMC, error) {
 	}
 	return contract, nil
 }
+
```
Comment (terenc3t) [inline sharding/client/client.go]: Can we add an overall function comment for `DepositFlagSet()`? 
Everything else looks good

Comment (prestonvanloon) [reply sharding/client/client.go]: Yeah good thinking
